config/routes.rb
HelloWorld::Application.routes.draw do
  namespace :api do
    namespace :v1 do
      resources :activity
        match "/woo" => "activity#woo"
        match "/exciting" => "activity#exciting"
        match "/nua" => "activity#nua"
    end
  end

  root :to => 'welcome#index' 
  resources :activity     
  match "/activity_text" => "welcome#text"
  match "/activity_auth" => "welcome#auth"
  match "/activity_mysubmission" => "activity#mysubmission" , :as => :my_submission
  match "/activity/:id/upvote" => "activity#upvote" , :as => :activity_upvote
  match "/activity/:id/downvote" => "activity#downvote"  , :as => :activity_downvote
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  

end

app/models/activity.rb
class Activity < ActiveRecord::Base
  attr_accessible :activity_image
  has_attached_file :activity_image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  attr_accessible :title, :description, :score, :country, :exciting, :address , :lat,:lon , :shortlocation, :shortactivity, :opening, :closing
  belongs_to :user
  def attachedimg_url
    if activity_image.file?
     activity_image.url
   else
     nil
  end    
  end
end

app/models/user.rb
require "open-uri"
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # , :confirmable,
  # :lockable, :timeoutable and 
  attr_accessible :avatar
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"

  devise :database_authenticatable, :registerable,:token_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable , :omniauthable , :omniauth_providers => [:facebook]
  attr_accessible :provider, :uid, :name, :email, :password, :password_confirmation, :remember_me  , :home_city,:home_country 
  has_many :activities


def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
  puts auth.inspect
  user = User.where(:provider => auth.provider, :uid => auth.uid).first
  unless user
    user = User.create(name:auth.extra.raw_info.name,
                         provider:auth.provider,
                         uid:auth.uid,
                         home_city: auth.extra.raw_info.hometown.name.split(",").first.strip(),
                         home_country: auth.extra.raw_info.hometown.name.split(",").last.strip(),
                         email:auth.info.email,
                         avatar:open(auth.info.image),
                         password:Devise.friendly_token[0,20]
                         )
  end
  user
end
  
  
end

app/controllers/activity_controller.rb
class ActivityController < ApplicationController
  
  before_filter :authenticate_user!
  def index
    if(params.has_key?(:user_show))
      @activities=current_user.activities
    else
      @hometown=current_user.home_city
      @activities = Activity.where('country'=>@hometown).order("score").reverse
    end
  end
  
  def mysubmission
    puts "hello world"
    redirect_to activity_index_path(:user_show => true)
  end

  
  def new
    @newActivity = Activity.new
    @hometown=current_user.home_city
  end

  def create
     @activity = Activity.new(params[:activity])
     @activity.score = 0;
     #@activity.country=current_user.home_city
     @activity.save
     
     current_user.activities << @activity
     current_user.save
     redirect_to activity_index_path

  end

  def update
    @updateActivity = Activity.find(params[:id])
    @updateActivity.update_attributes(params[:activity])
    @updateActivity.save
    redirect_to activity_path(@updateActivity.id)

  end

  def edit
    @editActivity = Activity.find(params[:id])
    
  end

  def destroy
    @deleteActivity = Activity.find(params[:id])
    @deleteActivity.delete
  end
  def upvote
    @activity = Activity.find(params[:id])
    @activity.score = @activity.score + 1 
    @activity.save
    redirect_to activity_index_path
  end
  def downvote
    @activity = Activity.find(params[:id])
    @activity.score = @activity.score - 1 
    @activity.save
    redirect_to activity_index_path
  end  
  def show
    @showActivity = Activity.find(params[:id])

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  #before_filter :authenticate_user!
  def index

  end
  def auth
    sid = "AC4af9426d4c30aaee027a1a4d9ec06ea1" 
    auth_token = "304378edb54f8286d6e22e53eb828941" 
    capability = Twilio::Util::Capability.new sid, auth_token 
    capability.allow_client_outgoing 'AP1de9b8812688c4f482a127423e6f1bd6'
    @token = capability.generate
    render :json => @token
  end
  
  def text
    @city = "Singapore"
    @state = "Singapore"
    render 'process.xml.erb', :content_type => 'text/xml'
  end
end

app/helpers/activity_helper.rb
module ActivityHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/activity/create.html.erb
<h1>Activity#create</h1>
<p>Find me in app/views/activity/create.html.erb</p>

app/views/activity/destroy.html.erb
<h1>Activity#destroy</h1>
<p>Find me in app/views/activity/destroy.html.erb</p>

app/views/activity/edit.html.erb
<div class="row">
  <div class="span12">
    <h1>Activity#edit</h1>
    <p>Find me in app/views/activity/edit.html.erb</p>
  </div>
</div>

<div class="row">
  <div class="span6">
    <%= simple_form_for(@editActivity,:url=>{ :action => "update" } ,:html=>{:class=>"span12", :mulitpart=>true }) do |f| %>
      <%= f.input :title, :required => true , :label=> "Title"%></br>
      <%= f.input :description,as: :text, :required => true , :label=> "Description"%></br></br>
      <%= f.input :country, collection: [ "Singapore", "Korea", "Thailand"], :required=>true%>
      <%= f.input :address, :required => false , :label=> "Address"%></br>
      <%= f.input :shortlocation, :required => false , :label=> "Location"%>
      <%= f.input :shortactivity, :required => false , :label=> "What to do"%>
      <%= f.input :lat, :required => false , :label=> "lat"%>
      <%= f.input :lon, :required => false , :label=> "lon"%>
      <%= f.input :activity_image, :label=> "Activity_Image"%></br>
      <%= f.input :exciting, :label=> "Exciting"%>

  </div>

    <div class="span6">

<%= f.input :opening, :required => false , :label=> "Opening Hour"%></br>
      <%= f.input :closing, :required => false , :label=> "Closing Hour"%></br>

    </div>
</div>

<div class="row">
  <div class="span12">
      <%= f.button :submit, "Update",class: "btn btn-large btn-primary" %></br>
      <%= link_to 'Cancel', activity_path(@editActivity.id) , class: "btn btn-large"%>
    <% end %>
  </div>
</div>

app/views/activity/index.html.erb
<div class="row">
  <div class="span12">
    <div class = "hero-unit">
    <h1>Activity#index in <%= current_user.home_city%></h1>
    <p>Find me in app/views/activity/index.html.erb</p>
    </div>
  </div>
</div>

<div class="row">
  <div class="span12">
    <%= link_to 'My Submissions', my_submission_path , class: "btn btn-large"%>
    <%= link_to 'Create a new Activity', new_activity_path , class: "btn btn-large pull-right"%>
  </div>
</div>

<% @activities.each do |activity|%>

<div class="well">
  <div class="container">
  <div class="row">
    <div class="span6">
      
      <h1><%= link_to activity.title, activity_path(activity.id) , class: ""%></h1>
      <h4>Description: <%= activity.description%></h4>
      <h4>Score: <%= activity.score%></h4>
      <%if activity.user %>
      <h4>Submitted By: <%= activity.user.name%></h4>
      <%end%>
      
    </div>
    <div class="span6">
      <%= image_tag activity.activity_image.url(:medium) %> <br>
    </div>
  </div>
    

<div class="row">
  <div class="span12">
  <%= link_to 'Upvote', activity_upvote_path(activity.id) , class: "btn btn-large"%>
  <%= link_to 'Downvote', activity_downvote_path(activity.id) , class: "btn btn-large"%>
  </div>
</div>
</div>
  </div>
<%end%>

<%= link_to 'Create a new Activity', new_activity_path , class: "btn btn-large"%>

app/views/activity/new.html.erb
<h1>Activity#new</h1>

<%= simple_form_for(@newActivity, :url => "/activity/",:html=>{:class=>"span8", :mulitpart=>true }) do |f| %>
	<%= f.input :title, :required => true , :label=> "Title"%>
  <%= f.input :description,as: :text, :required => true , :label=> "Description"%>
  <%= f.input :address, :required => false , :label=> "Address"%>
  <%= f.input :shortlocation, :required => false , :label=> "Location"%>
  <%= f.input :shortactivity, :required => false , :label=> "What to do"%>
  <%= f.input :lat, :required => false , :label=> "lat"%>
  <%= f.input :lon, :required => false , :label=> "lon"%>

  <p>Country: <%= @hometown%> </p>
  <%= f.input :activity_image, :label=> "Activity_Image"%>
    <%= f.input :exciting, :label=> "Exciting"%>
  <%= f.button :submit, "Submit!",class: "btn btn-large btn-primary" %>
  <%= link_to 'Cancel', activity_index_path , class: "btn btn-large"%>
<% end %>

app/views/activity/show.html.erb
<%= link_to 'All Activities', activity_index_path , class: "btn btn-large"%>
<h1>Title: <%= @showActivity.title %></h1>
<p><%= @showActivity.description %></p>
<p>Address: <%= @showActivity.address %></p>
<%= image_tag @showActivity.activity_image.url %> <br>
<%= link_to 'Edit Activity', edit_activity_path , class: "btn btn-large"%>
<%= link_to 'Back To Activities', activity_index_path , class: "btn btn-large"%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>HelloWorld</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= csrf_meta_tags %>


</head>
<body>

  <div class="container">
    <div class="masthead">
      <%= render 'layouts/user_header' %>
      <h1 class="muted"><%= link_to "Planno", root_path %></h1>
      <h5 class="muted">Brace Yourselves</h5>
    </div>
  </div>


    <hr />
  <div id="wrap">
    <div class="container">
  <%= yield %>
    </div>
  </div>
  
  <%= javascript_include_tag "application" %>
  <%= yield :scripts %>
  

</body>
</html>

app/views/welcome/index.html.erb
<div class="row">
  <div class="span10">
    <%if current_user%>
      <h1>Welcome <%= current_user.name%>!</h1>
      <%= image_tag current_user.avatar.url(:medium) %>
      <% else %>
      <h1>Welcome!</h1>
      <p>Find me in app/views/welcome/index.html.erb</p>
      <%end%>
    </div>
      <div class="span2">
    <%if current_user%>
        <%= link_to "View All Activities", activity_index_path,class: "btn" %>
        <%= link_to "Add Activity", new_activity_path,class: "btn" %>
    <%end%>
  </div>


</div>

<% if user_signed_in? %>
  
<% else %>

  <%= link_to image_tag("facebook.png", :border => 0), user_omniauth_authorize_path(:facebook) %>
  <button class="btn"><%= link_to "Sign in", new_user_session_path %></button>
  <li><%= link_to "Sign up", new_user_registration_path %></li>
  <li><%= link_to "Forgot Password", new_user_password_path , :method => :get %></li>
<% end %>


</div>